
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KKR
 */
public class Issue extends javax.swing.JFrame {

    /**
     * Creates new form Issue
     */
    public Issue() {
        super("Issue Book");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jTextFieldname = new javax.swing.JTextField();
        jTextFieldedition = new javax.swing.JTextField();
        jTextFieldpublisher = new javax.swing.JTextField();
        jTextFieldprice = new javax.swing.JTextField();
        jTextFieldpages = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldsid = new javax.swing.JTextField();
        jTextFieldsname = new javax.swing.JTextField();
        jTextFieldfather = new javax.swing.JTextField();
        jTextFieldbranch = new javax.swing.JTextField();
        jTextFieldyear = new javax.swing.JTextField();
        jTextFieldsemester = new javax.swing.JTextField();
        jTextFieldcourse = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Book ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 140, 70, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 190, 70, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Edition");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 240, 70, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Publisher");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 290, 71, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Price");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 340, 70, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Pages");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 390, 70, 22);
        jPanel1.add(jTextFieldid);
        jTextFieldid.setBounds(150, 132, 230, 30);
        jPanel1.add(jTextFieldname);
        jTextFieldname.setBounds(150, 190, 230, 30);
        jPanel1.add(jTextFieldedition);
        jTextFieldedition.setBounds(150, 240, 230, 30);
        jPanel1.add(jTextFieldpublisher);
        jTextFieldpublisher.setBounds(150, 290, 230, 30);
        jPanel1.add(jTextFieldprice);
        jTextFieldprice.setBounds(150, 340, 230, 30);
        jPanel1.add(jTextFieldpages);
        jTextFieldpages.setBounds(150, 390, 230, 30);

        jButton1.setIcon(new javax.swing.ImageIcon("F:\\library pics\\search.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(390, 130, 30, 30);

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Book Detail", 0, 0, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(0, 0, 204))); // NOI18N

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 334, Short.MAX_VALUE)
        );

        jPanel1.add(jLayeredPane1);
        jLayeredPane1.setBounds(20, 70, 420, 370);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Student ID");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(490, 140, 90, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(490, 190, 70, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Father Name");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(490, 240, 110, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Course");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(490, 290, 70, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Branch");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(490, 340, 70, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Year");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(490, 390, 60, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Semester");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(490, 440, 90, 20);
        jPanel1.add(jTextFieldsid);
        jTextFieldsid.setBounds(620, 140, 240, 30);

        jTextFieldsname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsnameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldsname);
        jTextFieldsname.setBounds(620, 190, 240, 30);
        jPanel1.add(jTextFieldfather);
        jTextFieldfather.setBounds(620, 240, 240, 30);
        jPanel1.add(jTextFieldbranch);
        jTextFieldbranch.setBounds(620, 340, 240, 30);
        jPanel1.add(jTextFieldyear);
        jTextFieldyear.setBounds(620, 390, 240, 30);
        jPanel1.add(jTextFieldsemester);
        jTextFieldsemester.setBounds(620, 440, 240, 30);
        jPanel1.add(jTextFieldcourse);
        jTextFieldcourse.setBounds(620, 290, 240, 30);

        jButton2.setIcon(new javax.swing.ImageIcon("F:\\library pics\\search.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(870, 140, 30, 30);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)), "Student Detail", 0, 0, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jPanel1.add(jLayeredPane2);
        jLayeredPane2.setBounds(480, 70, 440, 430);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Date of Issue");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(50, 480, 110, 22);
        jPanel1.add(jDateChooser);
        jDateChooser.setBounds(180, 480, 230, 30);

        jButton3.setBackground(new java.awt.Color(0, 204, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("Issue");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(540, 540, 79, 27);

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(739, 540, 70, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon("F:\\library pics\\issue.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 660);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldsnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsnameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        Home obj=new Home();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //String id=;
        //String name=jTextFieldname.getText();
        //String publisher=jTextFieldpublisher.getText();
        //String price=jTextFieldprice.getText();
        //String pages=jTextFieldpages.getText();
        PreparedStatement ps;
        ResultSet rs;
        String query="INSERT INTO `issue`(`book_id`, `name`, `edition`, `publisher`, `price`, `pages`, `student_id`, `sname`, `fname`, `course`, `branch`, `year`, `semester`, `date`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,jTextFieldid.getText());
            ps.setString(2, jTextFieldname.getText());
            ps.setString(3, jTextFieldedition.getText());
            ps.setString(4, jTextFieldpublisher.getText());
            ps.setString(5, jTextFieldprice.getText());
            ps.setString(6, jTextFieldpages.getText());
            ps.setString(7, jTextFieldsid.getText());
            ps.setString(8, jTextFieldsname.getText());
            ps.setString(9, jTextFieldfather.getText());
            ps.setString(10, jTextFieldcourse.getText());
            ps.setString(11, jTextFieldbranch.getText());
            ps.setString(12, jTextFieldyear.getText());
            ps.setString(13, jTextFieldsemester.getText());
            ps.setString(14, ((JTextField)jDateChooser.getDateEditor().getUiComponent()).getText());
         
            ps.execute();
            //if(rs.next()){
            JOptionPane.showMessageDialog(null, "Book Issued");
            //}
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PreparedStatement ps;
        ResultSet rs;
        String id=jTextFieldid.getText();
        String query="select * from book where Bookid='"+id+"'";
       
        try{
            ps=MyConnection.getConnection().prepareStatement(query);
            //ps.setString(1,id);
            rs=ps.executeQuery();
        if(rs.next()){
            jTextFieldname.setText(rs.getString(2));
            jTextFieldedition.setText(rs.getString(3));
            jTextFieldpublisher.setText(rs.getString(4));
            jTextFieldprice.setText(rs.getString(5));
            jTextFieldpages.setText(rs.getString(6));
            rs.close();
            ps.close();
        }
        else{
            JOptionPane.showMessageDialog(null,"Book ID not Found");
        }
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PreparedStatement ps;
        ResultSet rs;
        String sid=jTextFieldsid.getText();
        String query="select * from student where id='"+sid+"'";
       
        try{
            ps=MyConnection.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
        if(rs.next()){
            jTextFieldsname.setText(rs.getString(2));
            jTextFieldfather.setText(rs.getString(3));
            jTextFieldcourse.setText(rs.getString(4));
            jTextFieldbranch.setText(rs.getString(5));
            jTextFieldyear.setText(rs.getString(6));
            jTextFieldsemester.setText(rs.getString(7));
            rs.close();
            ps.close();
        }
        else{
            JOptionPane.showMessageDialog(null,"Student ID not Found");
        }
        }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Issue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldbranch;
    private javax.swing.JTextField jTextFieldcourse;
    private javax.swing.JTextField jTextFieldedition;
    private javax.swing.JTextField jTextFieldfather;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldpages;
    private javax.swing.JTextField jTextFieldprice;
    private javax.swing.JTextField jTextFieldpublisher;
    private javax.swing.JTextField jTextFieldsemester;
    private javax.swing.JTextField jTextFieldsid;
    private javax.swing.JTextField jTextFieldsname;
    private javax.swing.JTextField jTextFieldyear;
    // End of variables declaration//GEN-END:variables
}
