
import java.sql.PreparedStatement;
import java.sql.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author KKR
 */
public class Return extends javax.swing.JFrame {

    /**
     * Creates new form Return
     */
    public Return() {
        super("Return Book");
        setLocationRelativeTo(null);
        initComponents();
        setVisible(true);
    }

    public void Delete(){
        String sid=jTextFieldsid.getText();
        String bid=jTextFieldbid.getText();
        String query="delete from issue where student_id='"+sid+"' and book_id='"+bid+"'";
        PreparedStatement ps;
        ResultSet rs;
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Return.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void ReturnUpdate(){
        String query="INSERT INTO `return`(`student_id`, `name`, `fname`, `course`, `branch`, `year`, `semester`, `book_id`, `bname`, `edition`, `publisher`, `price`, `pages`, `DOI`, `DOR`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        PreparedStatement ps;
        ResultSet rs;
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            ps.setString(1,jTextFieldsid.getText());
            ps.setString(2, jTextFieldsname.getText());
            ps.setString(3, jTextFieldfname.getText());
            ps.setString(4, jTextFieldcourse.getText());
            ps.setString(5, jTextFieldbranch.getText());
            ps.setString(6, jTextFieldyear.getText());
            ps.setString(7, jTextFieldsemester.getText());
            ps.setString(8, jTextFieldbid.getText());
            ps.setString(9, jTextFieldname.getText());
            ps.setString(10, jTextFieldedition.getText());
            ps.setString(11, jTextFieldpublisher.getText());
            ps.setString(12, jTextFieldprice.getText());
            ps.setString(13, jTextFieldpages.getText());
            ps.setString(14, jTextFielddateofissue.getText());
            ps.setString(15, ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText());
         
            ps.execute();
            JOptionPane.showMessageDialog(null,"Book Returned");
            
        } catch (SQLException ex) {
            Logger.getLogger(Return.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelsid = new javax.swing.JLabel();
        jLabelname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldsid = new javax.swing.JTextField();
        jTextFieldsname = new javax.swing.JTextField();
        jTextFieldfname = new javax.swing.JTextField();
        jTextFieldcourse = new javax.swing.JTextField();
        jTextFieldbranch = new javax.swing.JTextField();
        jTextFieldyear = new javax.swing.JTextField();
        jTextFieldsemester = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldbid = new javax.swing.JTextField();
        jTextFieldname = new javax.swing.JTextField();
        jTextFieldedition = new javax.swing.JTextField();
        jTextFieldpublisher = new javax.swing.JTextField();
        jTextFieldprice = new javax.swing.JTextField();
        jTextFieldpages = new javax.swing.JTextField();
        jTextFielddateofissue = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Return Panel");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(340, 30, 250, 40);

        jLabelsid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelsid.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsid.setText("Student ID");
        jPanel2.add(jLabelsid);
        jLabelsid.setBounds(40, 140, 86, 22);

        jLabelname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelname.setForeground(new java.awt.Color(255, 255, 255));
        jLabelname.setText("Name");
        jPanel2.add(jLabelname);
        jLabelname.setBounds(40, 190, 45, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Father Name");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 240, 100, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Course");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 290, 54, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Branch");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 340, 54, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Year");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 390, 34, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Semester");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(40, 440, 80, 22);

        jTextFieldsid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextFieldsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsidActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldsid);
        jTextFieldsid.setBounds(150, 140, 220, 30);

        jTextFieldsname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel2.add(jTextFieldsname);
        jTextFieldsname.setBounds(150, 190, 220, 30);

        jTextFieldfname.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel2.add(jTextFieldfname);
        jTextFieldfname.setBounds(150, 240, 220, 30);

        jTextFieldcourse.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel2.add(jTextFieldcourse);
        jTextFieldcourse.setBounds(150, 290, 220, 30);

        jTextFieldbranch.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel2.add(jTextFieldbranch);
        jTextFieldbranch.setBounds(150, 340, 220, 30);

        jTextFieldyear.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel2.add(jTextFieldyear);
        jTextFieldyear.setBounds(150, 390, 220, 30);

        jTextFieldsemester.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel2.add(jTextFieldsemester);
        jTextFieldsemester.setBounds(150, 440, 220, 30);

        jButton1.setIcon(new javax.swing.ImageIcon("F:\\library pics\\search.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(840, 150, 30, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book ID");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(490, 150, 70, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(490, 200, 50, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Edition");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(490, 250, 60, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Publisher");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(490, 300, 80, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Price");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(490, 350, 40, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Pages");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(490, 400, 50, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Date of Issue");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(490, 450, 110, 22);
        jPanel2.add(jTextFieldbid);
        jTextFieldbid.setBounds(610, 150, 220, 30);
        jPanel2.add(jTextFieldname);
        jTextFieldname.setBounds(610, 200, 220, 30);
        jPanel2.add(jTextFieldedition);
        jTextFieldedition.setBounds(610, 250, 220, 30);
        jPanel2.add(jTextFieldpublisher);
        jTextFieldpublisher.setBounds(610, 300, 220, 30);
        jPanel2.add(jTextFieldprice);
        jTextFieldprice.setBounds(610, 350, 220, 30);
        jPanel2.add(jTextFieldpages);
        jTextFieldpages.setBounds(610, 400, 220, 30);
        jPanel2.add(jTextFielddateofissue);
        jTextFielddateofissue.setBounds(610, 450, 220, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(30, 510, 830, 10);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Return Date");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(40, 550, 100, 22);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(150, 550, 220, 30);

        jButton3.setBackground(new java.awt.Color(0, 204, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton3.setText("Return");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(490, 550, 75, 27);

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(670, 550, 63, 27);

        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("Please enter Student ID and Book ID then Search.");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(30, 100, 290, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\library pics\\return.jpg")); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 638);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(918, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String sid=jTextFieldsid.getText();
        String bid=jTextFieldbid.getText();
        String query="select * from issue where student_id='"+sid+"' and book_id='"+bid+"'";
        PreparedStatement ps;
        ResultSet rs;
        
        try {
            ps=MyConnection.getConnection().prepareStatement(query);
            rs=ps.executeQuery();
            if(rs.next()){
                jTextFieldsname.setText(rs.getString(8));
                jTextFieldfname.setText(rs.getString(9));
                jTextFieldcourse.setText(rs.getString(10));
                jTextFieldbranch.setText(rs.getString(11));
                jTextFieldyear.setText(rs.getString(12));
                jTextFieldsemester.setText(rs.getString(13));
                //jTextFieldbid.setText(rs.getString(1));
                jTextFieldname.setText(rs.getString(2));
                jTextFieldedition.setText(rs.getString(3));
                jTextFieldpublisher.setText(rs.getString(4));
                jTextFieldprice.setText(rs.getString(5));
                jTextFieldpages.setText(rs.getString(6));
                jTextFielddateofissue.setText(rs.getString(14));
            }
            else{
                JOptionPane.showMessageDialog(null,"Book is not Issued with this Student ID");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Delete();
        ReturnUpdate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home obj=new Home();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JLabel jLabelsid;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldbid;
    private javax.swing.JTextField jTextFieldbranch;
    private javax.swing.JTextField jTextFieldcourse;
    private javax.swing.JTextField jTextFielddateofissue;
    private javax.swing.JTextField jTextFieldedition;
    private javax.swing.JTextField jTextFieldfname;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextFieldpages;
    private javax.swing.JTextField jTextFieldprice;
    private javax.swing.JTextField jTextFieldpublisher;
    private javax.swing.JTextField jTextFieldsemester;
    private javax.swing.JTextField jTextFieldsid;
    private javax.swing.JTextField jTextFieldsname;
    private javax.swing.JTextField jTextFieldyear;
    // End of variables declaration//GEN-END:variables
}
